networks:
  ckh-network:
    name: ckh-network
    ipam:
      config:
        - subnet: 172.16.238.0/24
services:
  zookeeper-0:
    hostname: zookeeper-0
    container_name: zookeeper-0
    image: zookeeper:3.5
    networks:
      ckh-network:
        ipv4_address: 172.16.238.2
  clickhouse-0-0:
    hostname: clickhouse-0-0
    container_name: clickhouse-0-0
    image: clickhouse/clickhouse-server:23.4.2
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    networks:
      ckh-network:
        ipv4_address: 172.16.238.3
    volumes:
      - ${PWD}/volume/clickhouse-0-0:/etc/clickhouse-server
    depends_on:
      - zookeeper-0